"use strict";

// Rótulos de exibição dos países da PSD do café (USDA FAS, ADR 0031). O código é o `Country_Code` da própria PSD
// (FIPS 10-4, dois caracteres: Vietnã = VM, Brasil = BR), não o nome: o código não muda quando o USDA renomeia um
// país. Os 94 países do arquivo de 2026-09-28. A PSD do café não traz agregado mundial; a União Europeia é uma
// linha da fonte, como no WASDE. Um país que passe a existir sem constar aqui aparece com o código dele, sem quebrar.
const PAISES_PSD = {
  AL: "Albânia",
  AG: "Argélia",
  AO: "Angola",
  AR: "Argentina",
  AM: "Armênia",
  AS: "Austrália",
  DM: "Benin",
  BL: "Bolívia",
  BK: "Bósnia e Herzegovina",
  BR: "Brasil",
  BY: "Burundi",
  CM: "Camarões",
  CA: "Canadá",
  CT: "República Centro-Africana",
  CI: "Chile",
  CH: "China",
  CO: "Colômbia",
  CF: "Congo (Brazzaville)",
  CG: "Congo (Kinshasa)",
  CS: "Costa Rica",
  IV: "Costa do Marfim",
  HR: "Croácia",
  CU: "Cuba",
  DR: "República Dominicana",
  EC: "Equador",
  EG: "Egito",
  ES: "El Salvador",
  EK: "Guiné Equatorial",
  ET: "Etiópia",
  E4: "União Europeia",
  GB: "Gabão",
  GG: "Geórgia",
  GH: "Gana",
  GT: "Guatemala",
  GU: "Guiné",
  GY: "Guiana",
  HA: "Haiti",
  HO: "Honduras",
  IN: "Índia",
  ID: "Indonésia",
  IR: "Irã",
  JM: "Jamaica",
  JA: "Japão",
  JO: "Jordânia",
  KZ: "Cazaquistão",
  KE: "Quênia",
  KS: "Coreia do Sul",
  KV: "Kosovo",
  LA: "Laos",
  LI: "Libéria",
  MA: "Madagascar",
  MI: "Malawi",
  MY: "Malásia",
  MX: "México",
  MJ: "Montenegro",
  MO: "Marrocos",
  NC: "Nova Caledônia",
  NZ: "Nova Zelândia",
  NU: "Nicarágua",
  NI: "Nigéria",
  MK: "Macedônia do Norte",
  NO: "Noruega",
  PN: "Panamá",
  PP: "Papua-Nova Guiné",
  PA: "Paraguai",
  PE: "Peru",
  RP: "Filipinas",
  RS: "Rússia",
  RW: "Ruanda",
  SA: "Arábia Saudita",
  SG: "Senegal",
  RB: "Sérvia",
  SL: "Serra Leoa",
  SN: "Singapura",
  SF: "África do Sul",
  CE: "Sri Lanka",
  SZ: "Suíça",
  TW: "Taiwan",
  TZ: "Tanzânia",
  TH: "Tailândia",
  TO: "Togo",
  TD: "Trinidad e Tobago",
  TU: "Turquia",
  UG: "Uganda",
  UP: "Ucrânia",
  UK: "Reino Unido",
  US: "Estados Unidos",
  UY: "Uruguai",
  VE: "Venezuela",
  VM: "Vietnã",
  YM: "Iêmen",
  YE: "Iêmen (Sanaa)",
  ZA: "Zâmbia",
  RH: "Zimbábue"
};

function descreverPaisPsd(codigo) {
  return { rotulo: PAISES_PSD[codigo] ?? codigo, agregado: false };
}

module.exports = { PAISES_PSD, descreverPaisPsd };
